### ISSUE TITLE
not working on ipad or iphone(ios12.1)

### ISSUE THREAD

**Issue by cnrting** [theme-next/theme-next-needmoreshare2#14]
seems same as https://github.com/theme-next/theme-next-needmoreshare2/issues/7
nothing happened when clicking share button,but it works in chrome's mobile sumulation mode

config:
```
needmoreshare2:
  enable: true
  postbottom:
    enable: true
    options:
      iconStyle: box
      boxForm: horizontal
      position: middleCenter
      networks: Weibo,Wechat,Douban,QQZone,Twitter,Facebook,GooglePlus,Tumblr
  float:
    enable: false
    options:
      iconStyle: default
      boxForm: vertical
      position: leftCenter
      networks: Weibo,Wechat,Douban,QQZone,Twitter,Facebook,GooglePlus,Tumblr
```
