### ISSUE TITLE
Hexo+next使用整体无效果，页面不显示

### ISSUE THREAD

**Issue by weijiawei** [theme-next/theme-next-needmoreshare2#16]
主题配置文件配置如下：
```

needmoreshare2:
  enable: true
  postbottom:
    enable: true
    options:
      iconStyle: box
      boxForm: horizontal
      position: bottomCenter
      networks: Weibo,Wechat,Douban,QQZone,Twitter,Facebook
  float:
    enable: false
    options:
      iconStyle: box
      boxForm: horizontal
      position: middleRight
      networks: Weibo,Wechat,Douban,QQZone,Twitter,Facebook
```

这是界面图

![无效果图.png](https://ws1.sinaimg.cn/large/005XFOp3gy1gabkouucfmj31hc0q1jug.jpg)
