### ISSUE TITLE
Doesn't work in safari IOS11

### ISSUE THREAD

**Issue by Genuifx** [theme-next/theme-next-needmoreshare2#7]
I used needmoreshare2 in my hexo blog. https://genuifx.github.io/
but the share button doesn't work in safari or WeChat browser. Is this a bug or feature design?

**Comment by LEAFERx** [comment]
Can u upload some screenshots and describe more detailly?

**Comment by LEAFERx** [comment]
button works fine in my wechat browser but my phone is Android so I can't reproduce the problem.

**Comment by ivan-nginx** [comment]
@LEAFERx https://www.browserstack.com

**Comment by Genuifx** [comment]
just click the share button, and nothing expected happened.

here is my `_config.yml`
```yml
needmoreshare2:
  enable: true
  postbottom:
    enable: true
    options:
      iconStyle: box
      boxForm: horizontal
      position: bottomCenter
      networks: Weibo,Wechat,Douban,QQZone,Twitter,Facebook
  float:
    enable: true
    options:
      iconStyle: box
      boxForm: horizontal
      position: middleRight
      networks: Weibo,Wechat,Douban,QQZone,Twitter,Facebook
```
